# 50 Numpy Functions & Methods

## Initial Placeholders

In [7]:
# 1
import numpy as np
a1 = np.zeros(3)         # 1D array of length 3 all zeros
a2 = np.zeros((2,3))     # 2D array of all zeros
a3 = np.zeros((3,2,4))   # 3D array of all zeros
print("1D\n{}\n\n2D\n{}\n\n3D\n{}".format(a1,a2,a3))


1D
[0. 0. 0.]

2D
[[0. 0. 0.]
 [0. 0. 0.]]

3D
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [8]:
# 2
np.full((3,4),2)    # 3x4 array with all values 2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [9]:
# 3
np.random.rand(3,5)     # 3x5 array of random floats between 0-1

array([[0.59880796, 0.01951741, 0.41057068, 0.93431121, 0.76545238],
       [0.12064612, 0.77825983, 0.59848227, 0.17003048, 0.33651563],
       [0.47669949, 0.21367804, 0.46830507, 0.09449932, 0.44374235]])

In [10]:
# 4 
np.ones((3,4))      # 3x4 array with all values 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# 5 
np.eye(4)       # 4x4 array of 0 with 1 on diagonal


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Saving and Loading


In [13]:
# 6
# On disk:
x = np.array([1,2,3])
np.save("new_array",x)

In [14]:
# 7
np.load("new_array.npy")

array([1, 2, 3])

In [18]:
# 7
# Text/CSV files:
np.loadtxt("New_file.txt")  # From a text file

array([], dtype=float64)

In [19]:
# 8
np.genfromtxt('New_file.csv', delimiter=',')    # From a CSV file


array([], dtype=float64)

In [20]:
# 9 
arr = np.array([1,2,3,4,5,6,7,8])
np.savetxt('New_file.txt', arr, delimiter='')   # Writes to a text file

In [21]:
# 10
np.savetxt('New_file.csv', arr, delimiter=',') # Writes to a CSV file

In [25]:
# 11
array = np.array([[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]])
array.size  # Returns number of elements in array

16

In [26]:
# 12
array.shape # Returns dimensions of array (rows,columns)

(2, 8)

In [27]:
# 13 
array.dtype # returns type of elements in array

dtype('int32')

## Operations

In [28]:
# 14 
np.copy(array)  # Copies array to new memory array.

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
# 15
array.view(dtype=int)   # Creates view of array elements with type dtype

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
# 16
array.sort()    # Sorts array

In [40]:
# 17 
array.sort(axis=0)  # Sorts specific axis of array

In [46]:
# 18
array = np.array([1,2,3,4,5,6,7,8])
array.reshape(4,2)  # Reshapes array to 4 rows, 2 columns without changing data.

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
# 19
array = np.array([1,2,3,4,5,6,7,8])
np.append(array,values=(9,9,9))     # Appends values to end of array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9])

In [52]:
# 20
np.insert(array,4,values=(9,9,9))   # Inserts values into array before index 4. 

array([1, 2, 3, 4, 9, 9, 9, 5, 6, 7, 8])

In [74]:
# 21
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array = np.delete(array,2,axis=0)   # Deletes row on index 2 of array
print(f"Deleting rows\n {array}")
print('\n')
array = np.delete(array,3,axis=1)   # Deletes column on index 3 of array
print(f"Deleting columns\n {array}")

Deleting rows
 [[1 2 3 4]
 [5 6 7 8]]


Deleting columns
 [[1 2 3]
 [5 6 7]]


In [83]:
#22
array1 = np.array([[1,2,3,4],[1,1,1,1]])
array2 = np.array([[5,6,7,8],[9,10,11,12]])
r1 = np.concatenate((array1,array2),axis=0) # adds array2 as rows to the end of array1
print(f'Adds array2 as rows\n{r1}')
print("\n")
r2 = np.concatenate((array1,array2),axis=1) # adds array2 as columns to end of array1
print(f'Adds array2 as columns\n{r2}')

Adds array2 as rows
[[ 1  2  3  4]
 [ 1  1  1  1]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Adds array2 as columns
[[ 1  2  3  4  5  6  7  8]
 [ 1  1  1  1  9 10 11 12]]


In [107]:
# 23
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np.split(array,3)   # splits array into 3 sub-arrays

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [126]:
# 24
array = np.array([0,2,3,6])
a = array[0] = 6    # Assigns array element on index 0 the value 5
print(a)
print(array)

6
[6 2 3 6]


In [134]:
# 25
a = np.array([0,2,3,6,7,8,9])
a[3]

6

In [135]:
#26
a[0:4]

array([0, 2, 3, 6])

In [137]:
#27
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.add(a,b)

array([ 7,  9, 11, 13, 15])

In [138]:
#28
np.subtract(a,b)

array([-5, -5, -5, -5, -5])

In [139]:
#29
np.multiply(a,b)

array([ 6, 14, 24, 36, 50])

In [140]:
#30
np.divide(a,b)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [141]:
#31
np.exp(a)       # Exponentiation

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [142]:
#32
np.sqrt(a)      # Square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [143]:
#33
a==b    # element-wise

array([False, False, False, False, False])

In [144]:
#34
np.array_equal(a,b) # Array-wise

False

In [145]:
#35
a.sum() # Array-wise sum

15

In [146]:
#36
a.min()     # Array-wise min value

1

In [147]:
#37
a.max(axis=0)   # Array row max value

5

In [148]:
#38
a.mean()    # mean

3.0

In [152]:
#39
np.median(a)    # median

3.0

In [157]:
#40
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

np.vstack((a,b))    # To stack arrays along vertical axis

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [158]:
#41
np.hstack((a, b))   # To stack arrays along horizontal axis

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [159]:
#42
c = [5, 6]

np.column_stack((a, c)) # To stack 1-D arrays as columns into 2-D arrays


array([[1, 2, 5],
       [3, 4, 6]])

In [161]:
#43
np.concatenate((a, b), 1)   # To stack arrays along specified axis (axis is passed as argument)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [165]:
# 44
today = np.datetime64("2020-12-20")
print("Year is:", np.datetime64(today, 'Y'))

Year is: 2020


In [166]:
# 45
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

np.linalg.matrix_rank(A)    # Determines rank of a matrix

3

In [167]:
# 46
np.linalg.matrix_power(A, 3)    # Matrix A raised to power 3

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])

In [169]:
# 47
# linear equation
# x + 2*y = 8
# 3*x + 4*y = 18

# coefficients
a = np.array([[1, 2], [3, 4]])
# constants
b = np.array([8, 18])

c = np.linalg.solve(a, b)
print("Solution of linear equations: ", c)

Solution of linear equations:  [2. 3.]


In [175]:
# 48
array = np.array([1,2,3,4,5,6])

array.__lt__(4) #which element in an array is less then the value which is provided in the parameter

array([ True,  True,  True, False, False, False])

In [176]:
#49
arr = np.array([1, -2, 3, -4, 5, -7])

arr.__neg__()   # one can multiply each and every element of an array with -1. Hence, the resultant array having values like positive values becomes negative and negative values become positive.

array([-1,  2, -3,  4, -5,  7])

In [177]:
# 50
p_arr = np.array([1, 2, 3, 4, 5])

p_arr.__pow__(2) # every element get powered with the value that is provided as a parameter

array([ 1,  4,  9, 16, 25], dtype=int32)

In [185]:
# 51
resize_arr = np.array([1, 2, 3, 4, 5, 6])

np.resize(resize_arr, (2, 3))   # resizing of an array

array([[1, 2, 3],
       [4, 5, 6]])